import { useEffect, useMemo, useRef, useState } from "react";
import { emailNotifyAll } from "@/lib/emailNotifyAll";
import { motion } from "framer-motion";
import { FileText, Download, BatteryCharging, ArrowRightLeft, Activity, Sun, CheckCircle2, Loader2, FileBarChart, Calendar, PencilLine, Printer } from "lucide-react";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { useLanguage } from "@/contexts/LanguageContext";
import { useAuth } from "@/hooks/useAuth";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";

const API_SYSTEM = "https://lkxns0ebgc.execute-api.eu-west-3.amazonaws.com/data";
const API_BATTERY = "https://izn19wv78k.execute-api.eu-west-3.amazonaws.com/data";
const API_INVERTER = "https://qxpkkdx9p1.execute-api.eu-west-3.amazonaws.com/data";
const PRICE_PER_KWH = 2.25;
const STATION = { name: "Minya Solar Station", location: "Minya, Egypt", capacity: "~50 kWp" };

const r0 = (n: any) => Math.round(Number(n) || 0);
const r1 = (n: any) => Math.round((Number(n) || 0) * 10) / 10;
const r2 = (n: any) => Math.round((Number(n) || 0) * 100) / 100;
const fmt = (n: any) => r0(n).toLocaleString();
const safeFetch = async (u: string) => { try { const r = await fetch(u); return r.ok ? await r.json() : null; } catch { return null; } };
const toArr = (d: any) => Array.isArray(d) ? d : d ? [d] : [];
const cleanBat = (rec: any, field: string) => {
  const norm = (s: string) => s.replace(/[^\x00-\x7F]/g, "").trim().toLowerCase();
  const target = norm(field);
  for (const k of Object.keys(rec)) if (norm(k) === target) return rec[k];
  return null;
};

const PALETTE = {
  primary: [13, 110, 95] as [number, number, number],
  gold: [201, 168, 76] as [number, number, number],
  text: [30, 30, 30] as [number, number, number],
  muted: [110, 110, 110] as [number, number, number],
  ok: [34, 139, 84] as [number, number, number],
  warn: [217, 152, 35] as [number, number, number],
  err: [200, 60, 60] as [number, number, number],
  light: [245, 245, 245] as [number, number, number],
};

function header(doc: jsPDF, titleEn: string, titleAr: string, ar: boolean) {
  const W = doc.internal.pageSize.getWidth();
  doc.setFillColor(...PALETTE.primary);
  doc.rect(0, 0, W, 28, "F");
  doc.setFillColor(...PALETTE.gold);
  doc.rect(0, 28, W, 1.2, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text(ar ? titleAr : titleEn, 14, 13);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.text(`${STATION.name} · ${STATION.location} · ${STATION.capacity}`, 14, 21);
  doc.setFontSize(8);
  doc.text(new Date().toLocaleString(), W - 14, 13, { align: "right" });
  doc.text("Smart Solar Monitoring", W - 14, 21, { align: "right" });
}

function footer(doc: jsPDF) {
  const W = doc.internal.pageSize.getWidth();
  const H = doc.internal.pageSize.getHeight();
  const pages = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setDrawColor(...PALETTE.light);
    doc.line(14, H - 14, W - 14, H - 14);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...PALETTE.muted);
    doc.text("Generated by Smart Solar Dashboard · Minia University", 14, H - 8);
    doc.text(`Page ${i} / ${pages}`, W - 14, H - 8, { align: "right" });
  }
}

function sectionTitle(doc: jsPDF, y: number, en: string, ar: string, isAr: boolean) {
  doc.setFillColor(...PALETTE.primary);
  doc.rect(14, y - 4, 3, 6, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(...PALETTE.text);
  doc.text(isAr ? ar : en, 20, y);
  return y + 6;
}

function kpiGrid(doc: jsPDF, y: number, items: { label: string; value: string; tone?: "ok" | "warn" | "err" }[]) {
  const W = doc.internal.pageSize.getWidth();
  const cols = 4;
  const gap = 4;
  const w = (W - 28 - gap * (cols - 1)) / cols;
  const h = 22;
  items.forEach((it, i) => {
    const col = i % cols;
    const row = Math.floor(i / cols);
    const x = 14 + col * (w + gap);
    const yy = y + row * (h + gap);
    doc.setFillColor(...PALETTE.light);
    doc.roundedRect(x, yy, w, h, 2, 2, "F");
    const tone = it.tone === "ok" ? PALETTE.ok : it.tone === "warn" ? PALETTE.warn : it.tone === "err" ? PALETTE.err : PALETTE.primary;
    doc.setFillColor(...tone);
    doc.rect(x, yy, 1.5, h, "F");
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...PALETTE.muted);
    doc.text(it.label, x + 4, yy + 7);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(...PALETTE.text);
    doc.text(it.value, x + 4, yy + 16);
  });
  const rows = Math.ceil(items.length / cols);
  return y + rows * (h + gap);
}

type ReportKind = "summary" | "batteries" | "inverters" | "energy";

export default function Reports() {
  const { lang } = useLanguage();
  const ar = lang === "ar";
  const { user } = useAuth();
  const [busy, setBusy] = useState<ReportKind | null>(null);
  const [snapshot, setSnapshot] = useState<{ sys: any[]; bat: any[]; inv: any[] } | null>(null);
  const [loading, setLoading] = useState(true);
  const notified = useRef<Set<string>>(new Set());

  const [customTitle, setCustomTitle] = useState("");
  const [customAuthor, setCustomAuthor] = useState("");
  const [customBody, setCustomBody] = useState("");
  const [customBusy, setCustomBusy] = useState(false);

  const load = async () => {
    setLoading(true);
    const [s, b, i] = await Promise.all([safeFetch(API_SYSTEM), safeFetch(API_BATTERY), safeFetch(API_INVERTER)]);
    setSnapshot({ sys: toArr(s), bat: toArr(b), inv: toArr(i) });
    setLoading(false);
  };
  useEffect(() => { load(); const id = setInterval(load, 60_000); return () => clearInterval(id); }, []);

  const stats = useMemo(() => {
    if (!snapshot) return null;
    const sysLatest = snapshot.sys.length ? snapshot.sys.reduce((a: any, b: any) => new Date(b.Timestamp) > new Date(a.Timestamp) ? b : a) : null;
    const batMap = new Map<string, any>();
    snapshot.bat.forEach((r: any) => {
      const id = String(r.battery_id ?? "?");
      const ts = new Date(String(r.timestamp ?? "").trim()).getTime();
      const ex = batMap.get(id);
      if (!ex || ts > ex._ts) batMap.set(id, { ...r, _ts: ts });
    });
    const batLatest = [...batMap.values()];
    const invMap = new Map<string, any>();
    snapshot.inv.forEach((r: any) => {
      const id = String(r.inverter_id ?? r.InverterID ?? "?");
      const ts = new Date(String(r.timestamp ?? r.Timestamp ?? "").trim()).getTime();
      const ex = invMap.get(id);
      if (!ex || ts > ex._ts) invMap.set(id, { ...r, _ts: ts });
    });
    const invLatest = [...invMap.values()];
    return { sysLatest, batLatest, invLatest };
  }, [snapshot]);

  async function notify(kind: string, titleEn: string, titleAr: string, bodyEn: string, bodyAr: string) {
    if (!user) return;
    const key = `rep:${user.id}:${kind}:${Date.now()}`;
    if (notified.current.has(key)) return;
    notified.current.add(key);
    await (supabase as any).from("notifications").insert({
      user_id: user.id, kind: "report",
      title: ar ? titleAr : titleEn, body: ar ? bodyAr : bodyEn,
      link: "/dashboard/reports",
    });
    emailNotifyAll({ title: ar ? titleAr : titleEn, body: ar ? bodyAr : bodyEn, kind: "report" });
  }

  function buildSummary() {
    if (!stats) return null;
    const doc = new jsPDF({ unit: "mm", format: "a4" });
    header(doc, "System Summary Report", "تقرير ملخص النظام", ar);
    let y = 38;
    const sl = stats.sysLatest;
    const acP = sl ? r0(sl.Total_AC_PanelPower) : 0;
    const dcP = sl ? r0(sl.Total_DC_PanelPower) : 0;
    const eff = dcP > 0 ? Math.min(100, Math.round((acP / dcP) * 100)) : 0;
    const charge = sl ? r1(sl.TotalBatteryCharge) : 0;
    const health = (sl?.BATTERY_Health ?? "—").toString();
    const lowN = stats.batLatest.filter(b => (Number(cleanBat(b, "AverageCharge")) || 0) < 20).length;
    const fullN = stats.batLatest.filter(b => String(cleanBat(b, "IsFullCharge")).trim().toLowerCase() === "yes").length;

    y = sectionTitle(doc, y, "Live Snapshot", "اللقطة الحالية", ar);
    y = kpiGrid(doc, y, [
      { label: ar ? "قدرة AC" : "AC Power", value: `${fmt(acP)} W`, tone: acP > 0 ? "ok" : "warn" },
      { label: ar ? "قدرة DC" : "DC Power", value: `${fmt(dcP)} W`, tone: dcP > 0 ? "ok" : "warn" },
      { label: ar ? "الكفاءة" : "Efficiency", value: `${eff}%`, tone: eff >= 90 ? "ok" : eff >= 80 ? "warn" : "err" },
      { label: ar ? "شحن البطاريات" : "Battery Charge", value: `${charge}%`, tone: charge >= 50 ? "ok" : charge >= 25 ? "warn" : "err" },
      { label: ar ? "بطاريات ممتلئة" : "Full Batteries", value: String(fullN), tone: "ok" },
      { label: ar ? "بطاريات منخفضة" : "Low Batteries", value: String(lowN), tone: lowN > 0 ? "warn" : "ok" },
      { label: ar ? "حالة الأسطول" : "Fleet Health", value: health, tone: health.toUpperCase() === "CRITICAL" ? "err" : "ok" },
      { label: ar ? "آخر تحديث" : "Last Sync", value: sl ? new Date(sl.Timestamp).toLocaleTimeString() : "—" },
    ]);

    y += 4;
    y = sectionTitle(doc, y, "Voltage & Current", "الجهد والتيار", ar);
    autoTable(doc, {
      startY: y,
      head: [[ar ? "المقياس" : "Metric", ar ? "القيمة" : "Value", ar ? "الوحدة" : "Unit"]],
      body: [
        [ar ? "جهد AC الكلي" : "Total AC Voltage", r1(sl?.Total_AC_PanelVoltage), "V"],
        [ar ? "تيار AC الكلي" : "Total AC Current", r2(sl?.Total_AC_PanelCurrent), "A"],
        [ar ? "جهد DC الكلي" : "Total DC Voltage", r1(sl?.Total_DC_PanelVoltage), "V"],
        [ar ? "تيار DC الكلي" : "Total DC Current", r2(sl?.Total_DC_PanelCurrent), "A"],
        [ar ? "عدد البطاريات الممتلئة" : "Fully Charged Count", sl?.Fully_Charged_Count ?? 0, ""],
        [ar ? "عدد البطاريات المنخفضة" : "Low Battery Count", sl?.Low_Battery_Count ?? 0, ""],
      ],
      styles: { fontSize: 9, cellPadding: 2.5 },
      headStyles: { fillColor: PALETTE.primary, textColor: 255, fontStyle: "bold" },
      alternateRowStyles: { fillColor: [250, 250, 250] },
      margin: { left: 14, right: 14 },
    });
    footer(doc);
    return doc;
  }

  function buildBatteries() {
    if (!stats) return null;
    const doc = new jsPDF({ unit: "mm", format: "a4" });
    header(doc, "Batteries Report", "تقرير البطاريات", ar);
    let y = 38;
    const list = stats.batLatest.slice().sort((a, b) => String(a.battery_id).localeCompare(String(b.battery_id)));
    const totalCharge = list.length ? Math.round(list.reduce((s, b) => s + (Number(cleanBat(b, "AverageCharge")) || 0), 0) / list.length) : 0;
    const fullN = list.filter(b => String(cleanBat(b, "IsFullCharge")).trim().toLowerCase() === "yes").length;
    const lowN = list.filter(b => (Number(cleanBat(b, "AverageCharge")) || 0) < 20).length;
    const faultN = list.filter(b => String(b.status || "").toLowerCase() !== "ok").length;

    y = sectionTitle(doc, y, "Fleet Overview", "نظرة عامة على الأسطول", ar);
    y = kpiGrid(doc, y, [
      { label: ar ? "إجمالي البطاريات" : "Total Units", value: String(list.length), tone: "ok" },
      { label: ar ? "متوسط الشحن" : "Avg Charge", value: `${totalCharge}%`, tone: totalCharge >= 50 ? "ok" : "warn" },
      { label: ar ? "ممتلئة" : "Fully Charged", value: String(fullN), tone: "ok" },
      { label: ar ? "منخفضة" : "Low (<20%)", value: String(lowN), tone: lowN > 0 ? "warn" : "ok" },
      { label: ar ? "أعطال" : "Faults", value: String(faultN), tone: faultN > 0 ? "err" : "ok" },
    ]);

    y += 4;
    y = sectionTitle(doc, y, "Per-Battery Telemetry", "تليمتري كل بطارية", ar);
    autoTable(doc, {
      startY: y,
      head: [["ID", ar ? "شحن %" : "Charge %", ar ? "صحة" : "Health", ar ? "جهد V" : "Volt V", ar ? "تيار A" : "Curr A", ar ? "حرارة °C" : "Temp °C", ar ? "سعة Ah" : "Cap Ah", ar ? "الحالة" : "Status"]],
      body: list.map(b => {
        const charge = r0(cleanBat(b, "AverageCharge"));
        return [
          String(b.battery_id ?? "—"),
          `${charge}%`,
          `${r0(Number(cleanBat(b, "BatteryHealth")) * 10)}%`,
          r1(cleanBat(b, "Voltage")),
          r2(cleanBat(b, "Current")),
          r1(cleanBat(b, "Temperature")),
          r1(cleanBat(b, "Capacity")),
          String(b.status ?? "ok"),
        ];
      }),
      styles: { fontSize: 8.5, cellPadding: 2 },
      headStyles: { fillColor: PALETTE.primary, textColor: 255, fontStyle: "bold" },
      alternateRowStyles: { fillColor: [250, 250, 250] },
      margin: { left: 14, right: 14 },
    });
    footer(doc);
    return doc;
  }

  function buildInverters() {
    if (!stats) return null;
    const doc = new jsPDF({ unit: "mm", format: "a4" });
    header(doc, "Inverters Report", "تقرير المحولات", ar);
    let y = 38;
    const list = stats.invLatest.slice().sort((a, b) => String(a.inverter_id ?? a.InverterID).localeCompare(String(b.inverter_id ?? b.InverterID)));
    const acTot = list.reduce((s, x) => s + (Number(x.AC_Power) || 0), 0);
    const dcTot = list.reduce((s, x) => s + (Number(x.DC_Power) || 0), 0);
    const avgEff = list.length ? Math.round(list.reduce((s, x) => {
      const dc = Number(x.DC_Power) || 0; const ac = Number(x.AC_Power) || 0;
      return s + (dc > 0 ? Math.min(100, (ac / dc) * 100) : 0);
    }, 0) / list.length) : 0;
    const faultN = list.filter(x => String(x.status || "").toLowerCase() !== "ok").length;

    y = sectionTitle(doc, y, "Fleet Overview", "نظرة عامة على الأسطول", ar);
    y = kpiGrid(doc, y, [
      { label: ar ? "إجمالي AC" : "Total AC", value: `${fmt(acTot)} W`, tone: "ok" },
      { label: ar ? "إجمالي DC" : "Total DC", value: `${fmt(dcTot)} W`, tone: "ok" },
      { label: ar ? "متوسط الكفاءة" : "Avg Efficiency", value: `${avgEff}%`, tone: avgEff >= 90 ? "ok" : avgEff >= 80 ? "warn" : "err" },
      { label: ar ? "أعطال" : "Faults", value: String(faultN), tone: faultN > 0 ? "err" : "ok" },
    ]);

    y += 4;
    y = sectionTitle(doc, y, "Per-Inverter Telemetry", "تليمتري كل محول", ar);
    autoTable(doc, {
      startY: y,
      head: [["ID", "DC V", "DC A", "DC W", "AC V", "AC A", "AC W", ar ? "كفاءة %" : "Eff %", ar ? "الحالة" : "Status"]],
      body: list.map(x => {
        const dc = Number(x.DC_Power) || 0;
        const ac = Number(x.AC_Power) || 0;
        const eff = dc > 0 ? Math.min(100, Math.round((ac / dc) * 100)) : 0;
        return [
          String(x.inverter_id ?? x.InverterID ?? "—"),
          r1(x.DC_Voltage), r2(x.DC_Current), fmt(dc),
          r1(x.AC_Voltage), r2(x.AC_Current), fmt(ac),
          `${eff}%`, String(x.status ?? "ok"),
        ];
      }),
      styles: { fontSize: 8.5, cellPadding: 2 },
      headStyles: { fillColor: PALETTE.primary, textColor: 255, fontStyle: "bold" },
      alternateRowStyles: { fillColor: [250, 250, 250] },
      margin: { left: 14, right: 14 },
    });
    footer(doc);
    return doc;
  }

  function buildEnergy() {
    if (!stats) return null;
    const doc = new jsPDF({ unit: "mm", format: "a4" });
    header(doc, "Energy Production Report", "تقرير إنتاج الطاقة", ar);
    let y = 38;
    const pts = snapshot!.sys
      .map((r: any) => ({ wh: Number(r.Total_AC_PanelPower) || 0, ts: new Date(r.Timestamp).getTime() }))
      .filter(p => p.ts).sort((a, b) => a.ts - b.ts);
    const calcKWh = (arr: typeof pts) => {
      if (arr.length < 2) return 0;
      let kwh = 0;
      for (let i = 1; i < arr.length; i++) {
        const dtH = (arr[i].ts - arr[i - 1].ts) / 3_600_000;
        kwh += ((arr[i].wh + arr[i - 1].wh) / 2 * dtH) / 1000;
      }
      return kwh;
    };
    const now = Date.now();
    const day = pts.filter(p => p.ts >= now - 86_400_000);
    const week = pts.filter(p => p.ts >= now - 604_800_000);
    const month = pts.filter(p => p.ts >= now - 2_592_000_000);
    const year = pts.filter(p => p.ts >= now - 31_536_000_000);
    const ranges = [
      { k: ar ? "اليوم" : "Day", v: calcKWh(day) },
      { k: ar ? "الأسبوع" : "Week", v: calcKWh(week) },
      { k: ar ? "الشهر" : "Month", v: calcKWh(month) },
      { k: ar ? "السنة" : "Year", v: calcKWh(year) },
    ];

    y = sectionTitle(doc, y, "Energy & Revenue", "الطاقة والإيرادات", ar);
    y = kpiGrid(doc, y, ranges.map(r => ({
      label: r.k, value: `${r2(r.v)} kWh`, tone: "ok" as const,
    })));

    y += 4;
    y = sectionTitle(doc, y, "Estimated Revenue (EGP 2.25/kWh)", "الإيرادات التقديرية (2.25 ج.م/ك.و.س)", ar);
    autoTable(doc, {
      startY: y,
      head: [[ar ? "النطاق" : "Range", ar ? "الطاقة (ك.و.س)" : "Energy (kWh)", ar ? "الإيرادات (ج.م)" : "Revenue (EGP)"]],
      body: ranges.map(r => [r.k, r2(r.v).toLocaleString(), `EGP ${(r.v * PRICE_PER_KWH).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`]),
      styles: { fontSize: 9, cellPadding: 3 },
      headStyles: { fillColor: PALETTE.gold, textColor: 30, fontStyle: "bold" },
      alternateRowStyles: { fillColor: [250, 250, 250] },
      margin: { left: 14, right: 14 },
    });
    footer(doc);
    return doc;
  }

  async function generate(kind: ReportKind) {
    if (!stats) { toast.error(ar ? "لا توجد بيانات بعد" : "No data yet"); return; }
    setBusy(kind);
    try {
      const doc = kind === "summary" ? buildSummary() : kind === "batteries" ? buildBatteries() : kind === "inverters" ? buildInverters() : buildEnergy();
      if (!doc) throw new Error("build failed");
      const stamp = new Date().toISOString().slice(0, 10);
      const fname = `solar-${kind}-${stamp}.pdf`;
      doc.save(fname);
      toast.success(ar ? `تم إنشاء ${fname}` : `Generated ${fname}`);
      const titles: Record<ReportKind, [string, string]> = {
        summary: ["System summary report generated", "تم إنشاء تقرير ملخص النظام"],
        batteries: ["Batteries report generated", "تم إنشاء تقرير البطاريات"],
        inverters: ["Inverters report generated", "تم إنشاء تقرير المحولات"],
        energy: ["Energy report generated", "تم إنشاء تقرير الطاقة"],
      };
      await notify(kind, titles[kind][0], titles[kind][1],
        `File: ${fname}`, `الملف: ${fname}`);
    } catch (e: any) {
      toast.error(e?.message || "Failed");
    } finally {
      setBusy(null);
    }
  }

  const cards: { kind: ReportKind; icon: any; en: string; arT: string; descEn: string; descAr: string; gradient: string }[] = [
    { kind: "summary", icon: FileBarChart, en: "System Summary", arT: "ملخص النظام", descEn: "KPIs, voltage/current snapshot, fleet health.", descAr: "مؤشرات أداء، الجهد والتيار، حالة الأسطول.", gradient: "from-primary/20 to-primary/5" },
    { kind: "batteries", icon: BatteryCharging, en: "Batteries Report", arT: "تقرير البطاريات", descEn: "Per-unit charge, voltage, temperature, status.", descAr: "الشحن والجهد ودرجة الحرارة لكل بطارية.", gradient: "from-emerald-500/20 to-emerald-500/5" },
    { kind: "inverters", icon: ArrowRightLeft, en: "Inverters Report", arT: "تقرير المحولات", descEn: "DC↔AC power, efficiency, status per inverter.", descAr: "قدرة DC/AC والكفاءة لكل محول.", gradient: "from-amber-500/20 to-amber-500/5" },
    { kind: "energy", icon: Sun, en: "Energy & Revenue", arT: "الطاقة والإيرادات", descEn: "Day / Week / Month / Year kWh + EGP revenue.", descAr: "يوم / أسبوع / شهر / سنة بالكيلوواط ساعة + الإيراد.", gradient: "from-yellow-500/20 to-yellow-500/5" },
  ];

  function buildCustom() {
    const doc = new jsPDF({ unit: "mm", format: "a4" });
    const title = customTitle.trim() || (ar ? "تقرير مخصص" : "Custom Report");
    header(doc, title, title, ar);
    let y = 38;
    if (customAuthor.trim()) {
      doc.setFont("helvetica", "italic");
      doc.setFontSize(10);
      doc.setTextColor(...PALETTE.muted);
      doc.text(`${ar ? "بواسطة" : "By"}: ${customAuthor.trim()}`, 14, y);
      y += 6;
    }
    y = sectionTitle(doc, y + 2, "Report", "التقرير", ar);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(...PALETTE.text);
    const W = doc.internal.pageSize.getWidth();
    const H = doc.internal.pageSize.getHeight();
    const lines = doc.splitTextToSize(customBody.trim() || "—", W - 28);
    const lineH = 6;
    for (const line of lines) {
      if (y > H - 20) { doc.addPage(); y = 20; }
      doc.text(line, 14, y);
      y += lineH;
    }
    footer(doc);
    return doc;
  }

  async function generateCustom(action: "download" | "print") {
    if (!customBody.trim()) {
      toast.error(ar ? "اكتب محتوى التقرير أولاً" : "Write the report content first");
      return;
    }
    setCustomBusy(true);
    try {
      const doc = buildCustom();
      const stamp = new Date().toISOString().slice(0, 10);
      const fname = `custom-report-${stamp}.pdf`;
      if (action === "print") {
        doc.autoPrint();
        const url = doc.output("bloburl");
        window.open(url, "_blank");
      } else {
        doc.save(fname);
        toast.success(ar ? `تم إنشاء ${fname}` : `Generated ${fname}`);
      }
      await notify("custom",
        "Custom report generated", "تم إنشاء تقرير مخصص",
        `Title: ${customTitle || "Custom Report"}`,
        `العنوان: ${customTitle || "تقرير مخصص"}`);
    } catch (e: any) {
      toast.error(e?.message || "Failed");
    } finally {
      setCustomBusy(false);
    }
  }

  return (
    <div className="max-w-7xl mx-auto space-y-6">
      <motion.div initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }}>
        <Card className="relative overflow-hidden p-6 sm:p-8 bg-gradient-to-br from-primary/10 via-card to-accent/5 border-primary/20">
          <div className="absolute -top-20 -right-20 w-72 h-72 rounded-full opacity-10 blur-3xl" style={{ background: "hsl(var(--primary))" }} />
          <div className="relative flex flex-col sm:flex-row sm:items-center justify-between gap-4">
            <div className="space-y-2">
              <div className="flex items-center gap-2">
                <FileText className="w-5 h-5 text-primary" />
                <span className="text-xs font-bold uppercase tracking-widest text-primary">{ar ? "تقارير PDF" : "PDF Reports"}</span>
              </div>
              <h1 className="text-3xl sm:text-4xl font-black bg-gradient-to-r from-primary to-accent bg-clip-text text-transparent">
                {ar ? "تقارير المحطة" : "Station Reports"}
              </h1>
              <p className="text-sm text-muted-foreground max-w-2xl">
                {ar
                  ? "أنشئ تقارير PDF احترافية باستخدام أحدث البيانات اللحظية من المحطة (نظام، بطاريات، محولات، طاقة)."
                  : "Generate polished PDF reports built from the latest live data of the station — system, batteries, inverters and energy."}
              </p>
            </div>
            <div className="flex items-center gap-2 text-xs text-muted-foreground">
              {loading ? <Loader2 className="w-4 h-4 animate-spin" /> : <CheckCircle2 className="w-4 h-4 text-emerald-500" />}
              <span>{loading ? (ar ? "تحميل البيانات..." : "Loading data...") : (ar ? "البيانات جاهزة" : "Data ready")}</span>
            </div>
          </div>
        </Card>
      </motion.div>

      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        {cards.map((c, i) => (
          <motion.div key={c.kind} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.05 }}>
            <Card className={`group relative overflow-hidden p-6 h-full bg-gradient-to-br ${c.gradient} border-border hover:border-primary/40 transition-all`}>
              <div className="flex items-start justify-between gap-4">
                <div className="space-y-2 flex-1">
                  <div className="w-11 h-11 rounded-xl bg-background/60 backdrop-blur flex items-center justify-center border border-border">
                    <c.icon className="w-5 h-5 text-primary" />
                  </div>
                  <h3 className="text-lg font-bold">{ar ? c.arT : c.en}</h3>
                  <p className="text-sm text-muted-foreground">{ar ? c.descAr : c.descEn}</p>
                </div>
              </div>
              <div className="mt-5 flex items-center justify-between">
                <div className="flex items-center gap-1.5 text-[11px] text-muted-foreground">
                  <Calendar className="w-3.5 h-3.5" />
                  <span>{new Date().toLocaleDateString(ar ? "ar-EG" : undefined, { day: "numeric", month: "short", year: "numeric" })}</span>
                </div>
                <Button
                  size="sm"
                  onClick={() => generate(c.kind)}
                  disabled={busy !== null || loading || !stats}
                  className="gap-2"
                >
                  {busy === c.kind ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}
                  <span>{ar ? "تنزيل PDF" : "Download PDF"}</span>
                </Button>
              </div>
            </Card>
          </motion.div>
        ))}
      </div>

      <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }}>
        <Card className="relative overflow-hidden p-6 bg-gradient-to-br from-accent/10 via-card to-primary/5 border-primary/20">
          <div className="flex items-center gap-2 mb-4">
            <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center border border-primary/20">
              <PencilLine className="w-5 h-5 text-primary" />
            </div>
            <div>
              <h3 className="text-lg font-bold">{ar ? "اكتب تقريرك الخاص" : "Write Your Own Report"}</h3>
              <p className="text-xs text-muted-foreground">
                {ar ? "حرر المحتوى وحمّله PDF أو اطبعه مباشرة." : "Compose your content and download as PDF or print directly."}
              </p>
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div className="space-y-1.5">
              <Label htmlFor="custom-title">{ar ? "عنوان التقرير" : "Report Title"}</Label>
              <Input
                id="custom-title"
                value={customTitle}
                onChange={(e) => setCustomTitle(e.target.value)}
                placeholder={ar ? "مثلاً: ملاحظات الصيانة الأسبوعية" : "e.g. Weekly Maintenance Notes"}
                maxLength={120}
              />
            </div>
            <div className="space-y-1.5">
              <Label htmlFor="custom-author">{ar ? "بواسطة" : "Author"}</Label>
              <Input
                id="custom-author"
                value={customAuthor}
                onChange={(e) => setCustomAuthor(e.target.value)}
                placeholder={ar ? "اسمك" : "Your name"}
                maxLength={80}
              />
            </div>
          </div>

          <div className="space-y-1.5 mt-4">
            <Label htmlFor="custom-body">{ar ? "محتوى التقرير" : "Report Content"}</Label>
            <Textarea
              id="custom-body"
              value={customBody}
              onChange={(e) => setCustomBody(e.target.value)}
              placeholder={ar ? "اكتب التفاصيل، الملاحظات، التوصيات..." : "Write details, observations, recommendations..."}
              rows={8}
              maxLength={8000}
            />
            <div className="text-[11px] text-muted-foreground text-right">
              {customBody.length}/8000
            </div>
          </div>

          <div className="mt-4 flex flex-wrap items-center gap-2 justify-end">
            <Button
              variant="outline"
              onClick={() => generateCustom("print")}
              disabled={customBusy}
              className="gap-2"
            >
              {customBusy ? <Loader2 className="w-4 h-4 animate-spin" /> : <Printer className="w-4 h-4" />}
              <span>{ar ? "طباعة" : "Print"}</span>
            </Button>
            <Button
              onClick={() => generateCustom("download")}
              disabled={customBusy}
              className="gap-2"
            >
              {customBusy ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}
              <span>{ar ? "تنزيل PDF" : "Download PDF"}</span>
            </Button>
          </div>
        </Card>
      </motion.div>

      <Card className="p-5 bg-muted/30 border-border">
        <div className="flex items-start gap-3">
          <Activity className="w-5 h-5 text-primary mt-0.5" />
          <div className="space-y-1 text-sm">
            <p className="font-semibold">{ar ? "كيف تعمل التقارير؟" : "How reports work"}</p>
            <p className="text-muted-foreground">
              {ar
                ? "كل تقرير يُبنى لحظياً من بيانات AWS الحية ويحفظ كملف PDF على جهازك. كما يصلك إشعار تأكيدي بعد كل عملية إنشاء."
                : "Each report is built on the fly from live AWS data and saved to your device as a PDF. A confirmation notification is also sent after each generation."}
            </p>
          </div>
        </div>
      </Card>
    </div>
  );
}
